# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowPicker.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 947)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.index = QtWidgets.QWidget()
        self.index.setObjectName("index")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.index)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser_welcome_event = QtWidgets.QTextBrowser(self.index)
        self.textBrowser_welcome_event.setObjectName("textBrowser_welcome_event")
        self.horizontalLayout.addWidget(self.textBrowser_welcome_event)
        self.tableView_welcome_content = QtWidgets.QTableView(self.index)
        self.tableView_welcome_content.setObjectName("tableView_welcome_content")
        self.horizontalLayout.addWidget(self.tableView_welcome_content)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.textBrowser_welcome_log = QtWidgets.QTextBrowser(self.index)
        self.textBrowser_welcome_log.setObjectName("textBrowser_welcome_log")
        self.verticalLayout_6.addWidget(self.textBrowser_welcome_log)
        self.verticalLayout_6.setStretch(0, 8)
        self.verticalLayout_6.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.index)
        self.windows = QtWidgets.QWidget()
        self.windows.setObjectName("windows")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.windows)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.windows)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineEdit_window_width = QtWidgets.QLineEdit(self.windows)
        self.lineEdit_window_width.setObjectName("lineEdit_window_width")
        self.horizontalLayout_2.addWidget(self.lineEdit_window_width)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.windows)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.comboBox_windows_azimuth = QtWidgets.QComboBox(self.windows)
        self.comboBox_windows_azimuth.setMaxVisibleItems(10)
        self.comboBox_windows_azimuth.setObjectName("comboBox_windows_azimuth")
        self.horizontalLayout_10.addWidget(self.comboBox_windows_azimuth)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label = QtWidgets.QLabel(self.windows)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_p = QtWidgets.QCheckBox(self.windows)
        self.checkBox_p.setChecked(True)
        self.checkBox_p.setObjectName("checkBox_p")
        self.gridLayout_2.addWidget(self.checkBox_p, 0, 0, 1, 2)
        self.checkBox_s = QtWidgets.QCheckBox(self.windows)
        self.checkBox_s.setChecked(True)
        self.checkBox_s.setObjectName("checkBox_s")
        self.gridLayout_2.addWidget(self.checkBox_s, 0, 2, 1, 1)
        self.checkBox_ss = QtWidgets.QCheckBox(self.windows)
        self.checkBox_ss.setChecked(True)
        self.checkBox_ss.setObjectName("checkBox_ss")
        self.gridLayout_2.addWidget(self.checkBox_ss, 1, 0, 1, 1)
        self.checkBox_pp = QtWidgets.QCheckBox(self.windows)
        self.checkBox_pp.setChecked(True)
        self.checkBox_pp.setObjectName("checkBox_pp")
        self.gridLayout_2.addWidget(self.checkBox_pp, 1, 2, 1, 1)
        self.checkBox_sp = QtWidgets.QCheckBox(self.windows)
        self.checkBox_sp.setChecked(True)
        self.checkBox_sp.setObjectName("checkBox_sp")
        self.gridLayout_2.addWidget(self.checkBox_sp, 2, 0, 1, 1)
        self.checkBox_rayleigh = QtWidgets.QCheckBox(self.windows)
        self.checkBox_rayleigh.setChecked(True)
        self.checkBox_rayleigh.setObjectName("checkBox_rayleigh")
        self.gridLayout_2.addWidget(self.checkBox_rayleigh, 3, 0, 1, 2)
        self.checkBox_love = QtWidgets.QCheckBox(self.windows)
        self.checkBox_love.setChecked(True)
        self.checkBox_love.setObjectName("checkBox_love")
        self.gridLayout_2.addWidget(self.checkBox_love, 3, 2, 1, 1)
        self.checkBox_scs = QtWidgets.QCheckBox(self.windows)
        self.checkBox_scs.setChecked(True)
        self.checkBox_scs.setObjectName("checkBox_scs")
        self.gridLayout_2.addWidget(self.checkBox_scs, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_windows_length = QtWidgets.QLabel(self.windows)
        self.label_windows_length.setObjectName("label_windows_length")
        self.horizontalLayout_3.addWidget(self.label_windows_length)
        self.horizontalSlider_windows_length = QtWidgets.QSlider(self.windows)
        self.horizontalSlider_windows_length.setMinimum(100)
        self.horizontalSlider_windows_length.setMaximum(2400)
        self.horizontalSlider_windows_length.setSingleStep(100)
        self.horizontalSlider_windows_length.setPageStep(100)
        self.horizontalSlider_windows_length.setProperty("value", 1500)
        self.horizontalSlider_windows_length.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_windows_length.setTickInterval(100)
        self.horizontalSlider_windows_length.setObjectName("horizontalSlider_windows_length")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_windows_length)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_windows_normalize = QtWidgets.QCheckBox(self.windows)
        self.checkBox_windows_normalize.setObjectName("checkBox_windows_normalize")
        self.verticalLayout_2.addWidget(self.checkBox_windows_normalize)
        self.checkBox_windows_showsync = QtWidgets.QCheckBox(self.windows)
        self.checkBox_windows_showsync.setChecked(True)
        self.checkBox_windows_showsync.setObjectName("checkBox_windows_showsync")
        self.verticalLayout_2.addWidget(self.checkBox_windows_showsync)
        self.checkBox_windows_showdata = QtWidgets.QCheckBox(self.windows)
        self.checkBox_windows_showdata.setChecked(True)
        self.checkBox_windows_showdata.setObjectName("checkBox_windows_showdata")
        self.verticalLayout_2.addWidget(self.checkBox_windows_showdata)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.windows)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_windows_component = QtWidgets.QComboBox(self.windows)
        self.comboBox_windows_component.setObjectName("comboBox_windows_component")
        self.comboBox_windows_component.addItem("")
        self.comboBox_windows_component.addItem("")
        self.comboBox_windows_component.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_windows_component)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.windows)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.comboBox_windows_amplitude = QtWidgets.QComboBox(self.windows)
        self.comboBox_windows_amplitude.setObjectName("comboBox_windows_amplitude")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.comboBox_windows_amplitude.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_windows_amplitude)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.pushButton_windows_update = QtWidgets.QPushButton(self.windows)
        self.pushButton_windows_update.setObjectName("pushButton_windows_update")
        self.verticalLayout.addWidget(self.pushButton_windows_update)
        spacerItem = QtWidgets.QSpacerItem(20, 841, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.windows)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_windows_start = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_windows_start.setChecked(True)
        self.radioButton_windows_start.setObjectName("radioButton_windows_start")
        self.verticalLayout_7.addWidget(self.radioButton_windows_start)
        self.radioButton_windows_end = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_windows_end.setObjectName("radioButton_windows_end")
        self.verticalLayout_7.addWidget(self.radioButton_windows_end)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.windows)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton_windows_p = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_p.setChecked(True)
        self.radioButton_windows_p.setObjectName("radioButton_windows_p")
        self.gridLayout_6.addWidget(self.radioButton_windows_p, 0, 0, 1, 1)
        self.radioButton_windows_s = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_s.setObjectName("radioButton_windows_s")
        self.gridLayout_6.addWidget(self.radioButton_windows_s, 0, 1, 1, 1)
        self.radioButton_windows_ss = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_ss.setObjectName("radioButton_windows_ss")
        self.gridLayout_6.addWidget(self.radioButton_windows_ss, 1, 0, 1, 1)
        self.radioButton_windows_pp = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_pp.setObjectName("radioButton_windows_pp")
        self.gridLayout_6.addWidget(self.radioButton_windows_pp, 1, 1, 1, 1)
        self.radioButton_windows_sp = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_sp.setObjectName("radioButton_windows_sp")
        self.gridLayout_6.addWidget(self.radioButton_windows_sp, 2, 0, 1, 1)
        self.radioButton_windows_scs = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_scs.setObjectName("radioButton_windows_scs")
        self.gridLayout_6.addWidget(self.radioButton_windows_scs, 2, 1, 1, 1)
        self.radioButton_windows_rayleigh = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_rayleigh.setObjectName("radioButton_windows_rayleigh")
        self.gridLayout_6.addWidget(self.radioButton_windows_rayleigh, 3, 0, 1, 1)
        self.radioButton_windows_love = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_windows_love.setObjectName("radioButton_windows_love")
        self.gridLayout_6.addWidget(self.radioButton_windows_love, 3, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.pushButton_windows_select = QtWidgets.QPushButton(self.windows)
        self.pushButton_windows_select.setObjectName("pushButton_windows_select")
        self.verticalLayout.addWidget(self.pushButton_windows_select)
        self.pushButton_windows_remove = QtWidgets.QPushButton(self.windows)
        self.pushButton_windows_remove.setObjectName("pushButton_windows_remove")
        self.verticalLayout.addWidget(self.pushButton_windows_remove)
        self.pushButton_windows_save = QtWidgets.QPushButton(self.windows)
        self.pushButton_windows_save.setObjectName("pushButton_windows_save")
        self.verticalLayout.addWidget(self.pushButton_windows_save)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.windows)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.mplwidget_windows = MplWidget()
        self.mplwidget_windows.setGeometry(QtCore.QRect(0, 0, 948, 744))
        self.mplwidget_windows.setObjectName("mplwidget_windows")
        self.scrollArea.setWidget(self.mplwidget_windows)
        self.horizontalLayout_6.addWidget(self.scrollArea)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 20)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.textBrowser_windows_log = QtWidgets.QTextBrowser(self.windows)
        self.textBrowser_windows_log.setObjectName("textBrowser_windows_log")
        self.verticalLayout_4.addWidget(self.textBrowser_windows_log)
        self.verticalLayout_4.setStretch(0, 8)
        self.verticalLayout_4.setStretch(1, 1)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 0, 2, 2)
        self.stackedWidget.addWidget(self.windows)
        self.map = QtWidgets.QWidget()
        self.map.setObjectName("map")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.map)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_map = MplWidget(self.map)
        self.widget_map.setObjectName("widget_map")
        self.verticalLayout_13.addWidget(self.widget_map)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.textBrowser_map_log = QtWidgets.QTextBrowser(self.map)
        self.textBrowser_map_log.setObjectName("textBrowser_map_log")
        self.horizontalLayout_19.addWidget(self.textBrowser_map_log)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.map)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.comboBox_map_projection = QtWidgets.QComboBox(self.map)
        self.comboBox_map_projection.setObjectName("comboBox_map_projection")
        self.comboBox_map_projection.addItem("")
        self.comboBox_map_projection.addItem("")
        self.comboBox_map_projection.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_map_projection)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.map)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.comboBox_map_background = QtWidgets.QComboBox(self.map)
        self.comboBox_map_background.setObjectName("comboBox_map_background")
        self.comboBox_map_background.addItem("")
        self.comboBox_map_background.addItem("")
        self.comboBox_map_background.addItem("")
        self.comboBox_map_background.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_map_background)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.checkBox_map_beachball = QtWidgets.QCheckBox(self.map)
        self.checkBox_map_beachball.setObjectName("checkBox_map_beachball")
        self.horizontalLayout_16.addWidget(self.checkBox_map_beachball)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_map_select_stations = QtWidgets.QPushButton(self.map)
        self.pushButton_map_select_stations.setAutoDefault(False)
        self.pushButton_map_select_stations.setDefault(False)
        self.pushButton_map_select_stations.setFlat(False)
        self.pushButton_map_select_stations.setObjectName("pushButton_map_select_stations")
        self.horizontalLayout_18.addWidget(self.pushButton_map_select_stations)
        self.pushButton_map_reset = QtWidgets.QPushButton(self.map)
        self.pushButton_map_reset.setObjectName("pushButton_map_reset")
        self.horizontalLayout_18.addWidget(self.pushButton_map_reset)
        self.pushButton_map_update_figure = QtWidgets.QPushButton(self.map)
        self.pushButton_map_update_figure.setObjectName("pushButton_map_update_figure")
        self.horizontalLayout_18.addWidget(self.pushButton_map_update_figure)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_12)
        self.horizontalLayout_19.setStretch(0, 2)
        self.horizontalLayout_19.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.verticalLayout_13.setStretch(0, 8)
        self.verticalLayout_13.setStretch(1, 1)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.map)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTask = QtWidgets.QMenu(self.menubar)
        self.menuTask.setObjectName("menuTask")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionWelcome = QtWidgets.QAction(MainWindow)
        self.actionWelcome.setObjectName("actionWelcome")
        self.actionPick_Window = QtWidgets.QAction(MainWindow)
        self.actionPick_Window.setObjectName("actionPick_Window")
        self.actionMap = QtWidgets.QAction(MainWindow)
        self.actionMap.setObjectName("actionMap")
        self.actionInspect_waveforms = QtWidgets.QAction(MainWindow)
        self.actionInspect_waveforms.setObjectName("actionInspect_waveforms")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.actionsync_asdf_file = QtWidgets.QAction(MainWindow)
        self.actionsync_asdf_file.setObjectName("actionsync_asdf_file")
        self.actiondata_asdf_file = QtWidgets.QAction(MainWindow)
        self.actiondata_asdf_file.setObjectName("actiondata_asdf_file")
        self.menuFile.addAction(self.actionsync_asdf_file)
        self.menuFile.addAction(self.actiondata_asdf_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionInfo)
        self.menuTask.addAction(self.actionWelcome)
        self.menuTask.addAction(self.actionPick_Window)
        self.menuTask.addAction(self.actionMap)
        self.menuTask.addSeparator()
        self.menuHelp.addAction(self.actionShortcuts)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTask.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "width(°)"))
        self.lineEdit_window_width.setText(_translate("MainWindow", "15"))
        self.label_2.setText(_translate("MainWindow", "ranges(°)"))
        self.label.setText(_translate("MainWindow", "Mark travel times:"))
        self.checkBox_p.setText(_translate("MainWindow", "p/P"))
        self.checkBox_s.setText(_translate("MainWindow", "s/S"))
        self.checkBox_ss.setText(_translate("MainWindow", "sS/SS"))
        self.checkBox_pp.setText(_translate("MainWindow", "pP/PP"))
        self.checkBox_sp.setText(_translate("MainWindow", "sP/SP"))
        self.checkBox_rayleigh.setText(_translate("MainWindow", "Rayleigh"))
        self.checkBox_love.setText(_translate("MainWindow", "Love"))
        self.checkBox_scs.setText(_translate("MainWindow", "ScS"))
        self.label_windows_length.setText(_translate("MainWindow", "Length(1500s)"))
        self.checkBox_windows_normalize.setText(_translate("MainWindow", "Normalize"))
        self.checkBox_windows_showsync.setText(_translate("MainWindow", "Show sync"))
        self.checkBox_windows_showdata.setText(_translate("MainWindow", "Show data"))
        self.label_4.setText(_translate("MainWindow", "Component:"))
        self.comboBox_windows_component.setItemText(0, _translate("MainWindow", "vertical"))
        self.comboBox_windows_component.setItemText(1, _translate("MainWindow", "radial"))
        self.comboBox_windows_component.setItemText(2, _translate("MainWindow", "tangential"))
        self.label_3.setText(_translate("MainWindow", "amplitude:"))
        self.comboBox_windows_amplitude.setItemText(0, _translate("MainWindow", "1.0"))
        self.comboBox_windows_amplitude.setItemText(1, _translate("MainWindow", "0.2"))
        self.comboBox_windows_amplitude.setItemText(2, _translate("MainWindow", "0.4"))
        self.comboBox_windows_amplitude.setItemText(3, _translate("MainWindow", "0.6"))
        self.comboBox_windows_amplitude.setItemText(4, _translate("MainWindow", "0.8"))
        self.comboBox_windows_amplitude.setItemText(5, _translate("MainWindow", "1.2"))
        self.comboBox_windows_amplitude.setItemText(6, _translate("MainWindow", "1.6"))
        self.comboBox_windows_amplitude.setItemText(7, _translate("MainWindow", "1.8"))
        self.comboBox_windows_amplitude.setItemText(8, _translate("MainWindow", "2.0"))
        self.comboBox_windows_amplitude.setItemText(9, _translate("MainWindow", "3.0"))
        self.comboBox_windows_amplitude.setItemText(10, _translate("MainWindow", "4.0"))
        self.comboBox_windows_amplitude.setItemText(11, _translate("MainWindow", "5.0"))
        self.comboBox_windows_amplitude.setItemText(12, _translate("MainWindow", "10.0"))
        self.pushButton_windows_update.setText(_translate("MainWindow", "update"))
        self.groupBox.setTitle(_translate("MainWindow", "Select windows"))
        self.radioButton_windows_start.setText(_translate("MainWindow", "start"))
        self.radioButton_windows_end.setText(_translate("MainWindow", "end"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Phases for the window"))
        self.radioButton_windows_p.setText(_translate("MainWindow", "p/P"))
        self.radioButton_windows_s.setText(_translate("MainWindow", "s/S"))
        self.radioButton_windows_ss.setText(_translate("MainWindow", "sS/SS"))
        self.radioButton_windows_pp.setText(_translate("MainWindow", "pP/PP"))
        self.radioButton_windows_sp.setText(_translate("MainWindow", "sP/SP"))
        self.radioButton_windows_scs.setText(_translate("MainWindow", "ScS"))
        self.radioButton_windows_rayleigh.setText(_translate("MainWindow", "Rayleigh"))
        self.radioButton_windows_love.setText(_translate("MainWindow", "Love"))
        self.pushButton_windows_select.setText(_translate("MainWindow", "Select"))
        self.pushButton_windows_remove.setText(_translate("MainWindow", "Remove"))
        self.pushButton_windows_save.setText(_translate("MainWindow", "save"))
        self.label_10.setText(_translate("MainWindow", "Projection:"))
        self.comboBox_map_projection.setItemText(0, _translate("MainWindow", "Azimuthal Equidistant Projection"))
        self.comboBox_map_projection.setItemText(1, _translate("MainWindow", "Mercator Projection"))
        self.comboBox_map_projection.setItemText(2, _translate("MainWindow", "Equidistant Cylindrical Projection"))
        self.label_13.setText(_translate("MainWindow", "Background:"))
        self.comboBox_map_background.setItemText(0, _translate("MainWindow", "normal"))
        self.comboBox_map_background.setItemText(1, _translate("MainWindow", "NASA ‘Blue Marble’"))
        self.comboBox_map_background.setItemText(2, _translate("MainWindow", "shaded relief"))
        self.comboBox_map_background.setItemText(3, _translate("MainWindow", "etopo relief"))
        self.checkBox_map_beachball.setText(_translate("MainWindow", "BeachBall"))
        self.pushButton_map_select_stations.setText(_translate("MainWindow", "Select Stations"))
        self.pushButton_map_reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_map_update_figure.setText(_translate("MainWindow", "Update Figure"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTask.setTitle(_translate("MainWindow", "Task"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionWelcome.setText(_translate("MainWindow", "Welcome"))
        self.actionPick_Window.setText(_translate("MainWindow", "Pick Window"))
        self.actionMap.setText(_translate("MainWindow", "Map"))
        self.actionInspect_waveforms.setText(_translate("MainWindow", "Inspect waveforms"))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts"))
        self.actionsync_asdf_file.setText(_translate("MainWindow", "open sync file"))
        self.actiondata_asdf_file.setText(_translate("MainWindow", "open data file"))

from mplwidget import MplWidget
