# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_child.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_waveforms(object):
    def setupUi(self, waveforms):
        waveforms.setObjectName("waveforms")
        waveforms.resize(800, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(waveforms)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(waveforms)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_type = QtWidgets.QComboBox(waveforms)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_type)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(waveforms)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_network = QtWidgets.QLabel(waveforms)
        self.label_network.setText("")
        self.label_network.setObjectName("label_network")
        self.horizontalLayout_2.addWidget(self.label_network)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(waveforms)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_station = QtWidgets.QLabel(waveforms)
        self.label_station.setText("")
        self.label_station.setObjectName("label_station")
        self.horizontalLayout_3.addWidget(self.label_station)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_p = QtWidgets.QCheckBox(waveforms)
        self.checkBox_p.setChecked(True)
        self.checkBox_p.setObjectName("checkBox_p")
        self.gridLayout.addWidget(self.checkBox_p, 0, 0, 1, 1)
        self.checkBox_scs = QtWidgets.QCheckBox(waveforms)
        self.checkBox_scs.setChecked(True)
        self.checkBox_scs.setObjectName("checkBox_scs")
        self.gridLayout.addWidget(self.checkBox_scs, 2, 2, 1, 1)
        self.checkBox_pp = QtWidgets.QCheckBox(waveforms)
        self.checkBox_pp.setChecked(True)
        self.checkBox_pp.setObjectName("checkBox_pp")
        self.gridLayout.addWidget(self.checkBox_pp, 1, 2, 1, 1)
        self.checkBox_rayleigh = QtWidgets.QCheckBox(waveforms)
        self.checkBox_rayleigh.setChecked(True)
        self.checkBox_rayleigh.setObjectName("checkBox_rayleigh")
        self.gridLayout.addWidget(self.checkBox_rayleigh, 3, 0, 1, 2)
        self.checkBox_love = QtWidgets.QCheckBox(waveforms)
        self.checkBox_love.setChecked(True)
        self.checkBox_love.setObjectName("checkBox_love")
        self.gridLayout.addWidget(self.checkBox_love, 3, 2, 1, 1)
        self.checkBox_sp = QtWidgets.QCheckBox(waveforms)
        self.checkBox_sp.setChecked(True)
        self.checkBox_sp.setObjectName("checkBox_sp")
        self.gridLayout.addWidget(self.checkBox_sp, 2, 0, 1, 2)
        self.checkBox_ss = QtWidgets.QCheckBox(waveforms)
        self.checkBox_ss.setChecked(True)
        self.checkBox_ss.setObjectName("checkBox_ss")
        self.gridLayout.addWidget(self.checkBox_ss, 1, 0, 1, 2)
        self.checkBox_s = QtWidgets.QCheckBox(waveforms)
        self.checkBox_s.setChecked(True)
        self.checkBox_s.setObjectName("checkBox_s")
        self.gridLayout.addWidget(self.checkBox_s, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_length = QtWidgets.QLabel(waveforms)
        self.label_length.setObjectName("label_length")
        self.horizontalLayout_4.addWidget(self.label_length)
        self.horizontalSlider_length = QtWidgets.QSlider(waveforms)
        self.horizontalSlider_length.setMinimum(100)
        self.horizontalSlider_length.setMaximum(2400)
        self.horizontalSlider_length.setProperty("value", 1500)
        self.horizontalSlider_length.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_length.setObjectName("horizontalSlider_length")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_length)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.checkBox_show_sync = QtWidgets.QCheckBox(waveforms)
        self.checkBox_show_sync.setChecked(True)
        self.checkBox_show_sync.setObjectName("checkBox_show_sync")
        self.verticalLayout_2.addWidget(self.checkBox_show_sync)
        self.checkBox_show_data = QtWidgets.QCheckBox(waveforms)
        self.checkBox_show_data.setChecked(True)
        self.checkBox_show_data.setObjectName("checkBox_show_data")
        self.verticalLayout_2.addWidget(self.checkBox_show_data)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(waveforms)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_per_lap = QtWidgets.QLabel(waveforms)
        self.label_per_lap.setObjectName("label_per_lap")
        self.horizontalLayout_6.addWidget(self.label_per_lap)
        self.horizontalSlider_per_lap = QtWidgets.QSlider(waveforms)
        self.horizontalSlider_per_lap.setProperty("value", 90)
        self.horizontalSlider_per_lap.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_per_lap.setObjectName("horizontalSlider_per_lap")
        self.horizontalLayout_6.addWidget(self.horizontalSlider_per_lap)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(waveforms)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.lineEdit_max_sec = QtWidgets.QLineEdit(waveforms)
        self.lineEdit_max_sec.setObjectName("lineEdit_max_sec")
        self.horizontalLayout_10.addWidget(self.lineEdit_max_sec)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(waveforms)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.lineEdit_min_sec = QtWidgets.QLineEdit(waveforms)
        self.lineEdit_min_sec.setObjectName("lineEdit_min_sec")
        self.horizontalLayout_11.addWidget(self.lineEdit_min_sec)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(waveforms)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit_wlen = QtWidgets.QLineEdit(waveforms)
        self.lineEdit_wlen.setObjectName("lineEdit_wlen")
        self.horizontalLayout_5.addWidget(self.lineEdit_wlen)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.checkBox_log = QtWidgets.QCheckBox(waveforms)
        self.checkBox_log.setChecked(True)
        self.checkBox_log.setObjectName("checkBox_log")
        self.verticalLayout.addWidget(self.checkBox_log)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.widget_plot = MplWidget(waveforms)
        self.widget_plot.setObjectName("widget_plot")
        self.horizontalLayout_8.addWidget(self.widget_plot)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_map = QtWidgets.QWidget(waveforms)
        self.widget_map.setObjectName("widget_map")
        self.horizontalLayout_9.addWidget(self.widget_map)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_change_type = QtWidgets.QPushButton(waveforms)
        self.pushButton_change_type.setAutoDefault(False)
        self.pushButton_change_type.setObjectName("pushButton_change_type")
        self.horizontalLayout_7.addWidget(self.pushButton_change_type)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_update = QtWidgets.QPushButton(waveforms)
        self.pushButton_update.setAutoDefault(False)
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout_7.addWidget(self.pushButton_update)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 1)
        self.horizontalLayout_7.setStretch(4, 1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(waveforms)
        QtCore.QMetaObject.connectSlotsByName(waveforms)

    def retranslateUi(self, waveforms):
        _translate = QtCore.QCoreApplication.translate
        waveforms.setWindowTitle(_translate("waveforms", "Dialog"))
        self.label.setText(_translate("waveforms", "Type:"))
        self.comboBox_type.setItemText(0, _translate("waveforms", "waveform"))
        self.comboBox_type.setItemText(1, _translate("waveforms", "spectrogram"))
        self.label_2.setText(_translate("waveforms", "network:"))
        self.label_4.setText(_translate("waveforms", "station:"))
        self.checkBox_p.setText(_translate("waveforms", "p/P"))
        self.checkBox_scs.setText(_translate("waveforms", "ScS"))
        self.checkBox_pp.setText(_translate("waveforms", "pP/PP"))
        self.checkBox_rayleigh.setText(_translate("waveforms", "Rayleigh"))
        self.checkBox_love.setText(_translate("waveforms", "Love"))
        self.checkBox_sp.setText(_translate("waveforms", "sP/SP"))
        self.checkBox_ss.setText(_translate("waveforms", "sS/SS"))
        self.checkBox_s.setText(_translate("waveforms", "s/S"))
        self.label_length.setText(_translate("waveforms", "Length(1500s)"))
        self.checkBox_show_sync.setText(_translate("waveforms", "Show sync"))
        self.checkBox_show_data.setText(_translate("waveforms", "Show data"))
        self.label_9.setText(_translate("waveforms", "Spectrogram:"))
        self.label_per_lap.setText(_translate("waveforms", "per_lap(0.90)"))
        self.label_3.setText(_translate("waveforms", "max sec:"))
        self.lineEdit_max_sec.setText(_translate("waveforms", "120"))
        self.label_5.setText(_translate("waveforms", "min sec:"))
        self.lineEdit_min_sec.setText(_translate("waveforms", "20"))
        self.label_7.setText(_translate("waveforms", "wlen:"))
        self.checkBox_log.setText(_translate("waveforms", "log"))
        self.pushButton_change_type.setText(_translate("waveforms", "Change Type"))
        self.pushButton_update.setText(_translate("waveforms", "Update"))

from mplwidget import MplWidget
